server:
  port: 8080

spring:
  application:
    name: G2WebStoreV2

  datasource:
    url: jdbc:mysql://localhost:3306/g2db_test
    username: root
    password: khanh1307
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

  mail:
    host: smtp.gmail.com
    username: g2storehcmute@gmail.com
    password: pcza anwx fhou zblz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gcp:
  config:
    file: g2-test-project-05bf49dd9bfb.json
  project:
    id: g2-test-project
  bucket:
    id: demo-bucket-g2

application:
  security:
    jwt:
      secret-key: eOAmtX442iArmtlrIsSpKtlEEaw0zg7+OUy7/Qv0qVFmA0rEHrFtlmtW8XPfm/5/jCJ5AdmMijQhfarcqU57Sg==
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days