server:
  port: 8080

spring:
  application:
    name: G2WebStoreV2

  datasource:
    url: jdbc:mysql://localhost:3306/g2db_test
    username: root
    password: khanh1307
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

  mail:
    host: smtp.gmail.com
    username: g2storehcmute@gmail.com
    password: pcza anwx fhou zblz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gcp:
  config:
    file: YOUR_KEY
  project:
    id: g2webstore
  bucket:
    id: g2_web_store_data
  gcs:
    url-prefix: https://storage.googleapis.com/

firebase:
  key: g2-web-store-firebase-adminsdk-9197j-055d542a1c.json
  project: g2-web-store
  storage:
    bucket: g2-web-store.appspot.com
    url: https://firebasestorage.googleapis.com/v0/b/

vnp:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/v1/payments/return-url
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  tmn-code: 9279QT0C
  secret-key: RIPBIASTCZTZNUAOQYTKVZDTBLAKOMOR
  version: 2.1.0

captcha:
  secret: 6Lcdz8cpAAAAAPYumczXzpVgiX_5G_vHzcrQo7rC
  url: https://www.google.com/recaptcha/api/siteverify

ghn:
  token: da8bac8e-9519-11ee-8bfa-8a2dda8ec551
  shop-id: 190509
  fee-ship-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee
  expected-delivery-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/leadtime
  create-order-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/create
  print-order:
    return-url:
      printA5: https://dev-online-gateway.ghn.vn/a5/public-api/printA5?token=
      print80x80: https://dev-online-gateway.ghn.vn/a5/public-api/print80x80?token=
      print50x72: https://dev-online-gateway.ghn.vn/a5/public-api/print52x70?token=
    url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/a5/gen-token

application:
  security:
    jwt:
      secret-key: eOAmtX442iArmtlrIsSpKtlEEaw0zg7+OUy7/Qv0qVFmA0rEHrFtlmtW8XPfm/5/jCJ5AdmMijQhfarcqU57Sg==
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days