package com.hcmute.g2webstorev2.enums;

public enum AppPermission {
    CREATE_PROMOTION, READ_PROMOTION, UPDATE_PROMOTION, DELETE_PROMOTION,
    CREATE_PRODUCT, READ_PRODUCT, UPDATE_PRODUCT, DELETE_PRODUCT,
    CREATE_ORDER, READ_ORDER, UPDATE_ORDER, DELETE_ORDER,
    CREATE_REVIEW, READ_REVIEW, UPDATE_REVIEW, DELETE_REVIEW,
    CREATE_USER, READ_USER, UPDATE_USER, DELETE_USER,
    CREATE_CATEGORY, READ_CATEGORY, UPDATE_CATEGORY, DELETE_CATEGORY
}
