package com.hcmute.g2webstorev2.enums;

public enum AppRole {
    ADMIN,
    CUSTOMER,
    SELLER_PROMOTION_ACCESS,
    SELLER_PRODUCT_ACCESS,
    JUNIOR_CHAT_AGENT,
    SELLER_ORDER_MANAGEMENT,
    SELLER_FULL_ACCESS,
    SELLER_READ_ONLY
}
